# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: kazuna1.Slate
PackageVersion: 1.0.0
InstallerLocale: en-US
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
AppsAndFeaturesEntries:
- DisplayName: Slate
  Publisher: Tuguldur Munkhbat
  ProductCode: '{7B3F0C2E-5A8D-4E61-9C1B-2F4D8A6E9B10}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/kazuna1/slate/releases/download/v1.0.0/SlateSetup.exe
  InstallerSha256: 55D60E7007635873D7D73AE050371F734755DC6B8850EA573EAEEA4706E2CC84
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2026-10-01
